[package]
name = "tq"
version = "0.1.0"
authors = ["Eyal Kalderon <ebkalderon@gmail.com>"]
description = "Command-line TOML parser similar to jq"

[dependencies]
env_logger = "0.5"
failure = "0.1"
log = "0.4"
pest = "1.0"
pest_derive = "1.0"
structopt = "0.2"
toml = "0.4"
